services:
  - name: app
    type: web
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: fastapi run main.py --host 0.0.0.0 --port $PORT